---
# Source: gha-runner-scale-set/templates/no_permission_serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-action-runner-gha-rs-no-permission
  namespace: gha-runner
  labels:
    helm.sh/chart: gha-rs-0.13.1
    app.kubernetes.io/name: jenkins-action-runner
    app.kubernetes.io/instance: jenkins-action-runner
    app.kubernetes.io/version: "0.13.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: gha-rs
    actions.github.com/scale-set-name: jenkins-action-runner
    actions.github.com/scale-set-namespace: gha-runner
  annotations:
  finalizers:
    - actions.github.com/cleanup-protection
---
# Source: gha-runner-scale-set/templates/manager_role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-action-runner-gha-rs-manager
  namespace: gha-runner
  labels:
    helm.sh/chart: gha-rs-0.13.1
    app.kubernetes.io/name: jenkins-action-runner
    app.kubernetes.io/instance: jenkins-action-runner
    app.kubernetes.io/version: "0.13.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: gha-rs
    actions.github.com/scale-set-name: jenkins-action-runner
    actions.github.com/scale-set-namespace: gha-runner
    app.kubernetes.io/component: manager-role
  annotations:
  finalizers:
    - actions.github.com/cleanup-protection
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  verbs:
  - create
  - delete
  - get
  - patch
  - update
---
# Source: gha-runner-scale-set/templates/manager_role_binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-action-runner-gha-rs-manager
  namespace: gha-runner
  labels:
    helm.sh/chart: gha-rs-0.13.1
    app.kubernetes.io/name: jenkins-action-runner
    app.kubernetes.io/instance: jenkins-action-runner
    app.kubernetes.io/version: "0.13.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: gha-rs
    actions.github.com/scale-set-name: jenkins-action-runner
    actions.github.com/scale-set-namespace: gha-runner
    app.kubernetes.io/component: manager-role-binding
  annotations:
  finalizers:
    - actions.github.com/cleanup-protection
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins-action-runner-gha-rs-manager
subjects:
- kind: ServiceAccount
  name: 
    actions-controller
  namespace: 
    gha-controller
---
# Source: gha-runner-scale-set/templates/autoscalingrunnerset.yaml
apiVersion: actions.github.com/v1alpha1
kind: AutoscalingRunnerSet
metadata:
  name: jenkins-action-runner
  namespace: gha-runner
  labels:
    app.kubernetes.io/component: "autoscaling-runner-set"
    helm.sh/chart: gha-rs-0.13.1
    app.kubernetes.io/name: jenkins-action-runner
    app.kubernetes.io/instance: jenkins-action-runner
    app.kubernetes.io/version: "0.13.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: gha-rs
    actions.github.com/scale-set-name: jenkins-action-runner
    actions.github.com/scale-set-namespace: gha-runner
  annotations:
    actions.github.com/values-hash: d82d928c93063161f0909ea6c3a1518d8be51a7df39d71369600070d7aaaad7
    actions.github.com/cleanup-manager-role-binding: jenkins-action-runner-gha-rs-manager
    actions.github.com/cleanup-manager-role-name: jenkins-action-runner-gha-rs-manager
    actions.github.com/cleanup-no-permission-service-account-name: jenkins-action-runner-gha-rs-no-permission

spec:
  githubConfigUrl: https://github.com/Yogeshwaran-Palanisamy/jenkins
  githubConfigSecret: controller-manager

  template:
    spec:
      restartPolicy: Never
      serviceAccountName: jenkins-action-runner-gha-rs-no-permission
      containers:
      
      - name: runner
        command: 
          - /home/runner/run.sh
        image: 
          ghcr.io/actions/actions-runner:latest
