
{{- if .Values.rbac.enabled | default false -}}
{{- range $val := .Values.rbac.roles }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: {{$val.name}}
rules:
- apiGroups:
{{- toYaml $val.apiGroups | nindent 2 }}
  resources:
{{- toYaml $val.resources | nindent 2 }}
  verbs:
{{- toYaml $val.verbs | nindent 2 }}
{{- end}}
{{- end -}}