{{- if .Values.secrets.enabled | default false -}}

{{- range $name, $data := .Values.secrets.values }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  namespace: {{ $data.namespace }}
type: Opaque
data:
{{- range $key, $val := $data }}
  {{- if not (eq $key "namespace")}}
  {{ $key }}: {{ $val | quote }}
  {{- end}}
{{- end }}
---
{{- end }}
{{- end -}}